### ISSUE TITLE
Add grading screen 

### ISSUE THREAD

**Issue by J-Guillaume** [J-Guillaume/PlutoHacks23#10]
Once the interview is over display a screen that shows the user how they did in the interview

Pass - 5/5 to 3/5
Fail - 2/5 to 0/5

**Comment by J-Guillaume** [comment]
![Result Screens](https://github.com/J-Guillaume/PlutoHacks23/assets/55116512/6e8dfb0b-5490-4b31-8569-7e5005d128ad)

Here is an outline i created on Figma

**Comment by jcinek** [comment]
new code provides difficulty level of prompted question as opposed to grading scale
